apiVersion: 1
datasources:
  - name: OpenSearch-Zeek
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    database: "zeek-*"
    isDefault: true
    jsonData:
      timeField: "ts"
      version: "2.11.0"
      flavor: "opensearch"
      logMessageField: ""
      logLevelField: ""
    editable: false

  - name: OpenSearch-Suricata
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    database: "suricata-*"
    jsonData:
      timeField: "timestamp"
      version: "2.11.0"
      flavor: "opensearch"
    editable: false
